# Generated by Django 5.2.7 on 2025-10-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_categoria_imagen_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='resumen',
            field=models.CharField(blank=True, help_text='Texto breve que se mostrará en el catálogo (máx. 160 caracteres).', max_length=160, verbose_name='resumen corto (para la tarjeta)'),
        ),
    ]
