# Generated by Django 5.2.7 on 2025-11-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_producto_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_usuario',
            field=models.PositiveIntegerField(default=0, help_text='Número correlativo de pedido para este usuario'),
        ),
    ]
